apiVersion: v1
kind: Service
metadata:
  name: guestbook-ui-stage
  labels:
    app: guestbook-ui-stage
spec:
  type: ClusterIP
  selector:
    app: guestbook-ui-stage
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP

