apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook-ui-dev
  labels:
    app: guestbook-ui-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook-ui-dev
  template:
    metadata:
      labels:
        app: guestbook-ui-dev
    spec:
      containers:
      - name: guestbook-ui
        image: gcr.io/google-samples/gb-frontend:v5
        ports:
        - containerPort: 80

