apiVersion: v1
kind: Service
metadata:
  annotations:
    argocd.argoproj.io/tracking-id: guestbook-app:/Service:default/guestbook-ui
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"guestbook-app:/Service:default/guestbook-ui"},"name":"guestbook-ui","namespace":"default"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"guestbook-ui"}}}
  creationTimestamp: "2025-12-25T04:18:12Z"
  name: guestbook-ui
  namespace: default
  resourceVersion: "239385"
  uid: 911c28d7-6543-43dd-9513-2d7f1d35eb26
spec:
  clusterIP: 10.96.103.110
  clusterIPs:
  - 10.96.103.110
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: guestbook-ui
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
